### ISSUE TITLE
upload images to s3

### ISSUE THREAD

**Issue by joamatab** [hedgedoc/container#12]
how can we switch to save images in s3 instead of imgur?

**Comment by SISheogorath** [comment]
Sure, check our Guide for S3: https://github.com/hackmdio/codimd/blob/97a08e7954af01719bb2519e863fdf5990d4d56f/docs/guides/s3-image-upload.md

Just make sure you use the environment variables for configuration instead (mentioned at the end). If you need further help feel free to reach out to [our community channel](https://riot.im/app/#/room/#codimd:matrix.org)
