### ISSUE TITLE
Migrating codimd to hedgedoc with apache reverse proxy

### ISSUE THREAD

**Issue by JayDee2202** [hedgedoc/container#142]
I migrated several instances of codimd 2.2.0 to hedgedoc 1.7.1.
The instances with a traefik proxy could be migrated very easily and worked immediately.

An instance with apache2 (v2.4.38) as reverse proxy did not work after the upgrade. A login was not possible, the page reloaded and nothing happened. Temporary guest notes could not be created either, it seemed that no database access was possible.

After some research, I found out through the logs that a "serializeUser" could be executed, but not a "deserializeUser". After testing various permissions and temporarily downgrading the postgres database back from 11.6 to 9.6 and removing all volumes, it still did not work.

After resetting to all default values within the compose file I got instances working again and now I know what the problem was:
The environment variables `CMD_DOMAIN` and `CMD_PROTOCOL_USESSL=true` were set. Without these two the instance worked again. The traefik installations still works with these environment variables, as does CodiMD version 2.2.0 (`nabo.codimd.dev/hackmdio/hackmd:2.2.0`).

So, there still seems to be a difference here, which partly restricts the usage.

**Comment by davidmehren** [comment]
Apache by default does not set the `X-Forwarded-Proto` header, which leads to HedgeDoc not setting login cookies when `protocolUseSSL` is enabled (we discovered that in [this issue](https://github.com/hedgedoc/hedgedoc/issues/616)).
Have a look at [the docs](https://github.com/hedgedoc/hedgedoc/blob/72734690225bb431908b0d4bd8edf38576a95f2f/docs/setup/reverse-proxy.md#reverse-proxy-config) for a working Apache config.

We also added a note about that header in the changelog of 1.7.0, maybe we should make it bigger? :wink:

**Comment by JayDee2202** [comment]
Thanks for the quick reply!

I'll be honest and admit that I didn't read the release notes of version 1.7.0 completely and just followed the relatively simple [upgrade guide](https://github.com/hedgedoc/container#migrate-from-docker-hackmd).
That was actually the reason for my surprise, especially since the other upgrades went through without a hitch. Perhaps a hint there would still be helpful. :)

**Comment by hugopeixoto** [comment]
Instead of "Now you can follow the regular update steps.", we could add a link to the release notes. This would at least prompt folks to read them. I'll make a PR updating the README.
