### ISSUE TITLE
Picture uploaded to local issue 

### ISSUE THREAD

**Issue by qianzai** [hedgedoc/container#146]
您好~

​		HedgeDoc是非常好用，但是我使用docker部署遇到了如下的问题，找了很多但是都没有解决

1、开始启动docker-compose他报了如下警告，

![image](https://user-images.githubusercontent.com/46664739/104400264-30a80700-558d-11eb-97d0-c6e947113547.png)

2、当我在插入图片的时候他并没有返回正确的地址
![image](https://user-images.githubusercontent.com/46664739/104400336-4ae1e500-558d-11eb-9fe2-5d929e759aa2.png)

3、但是我发现在docker 容器内图片已经是上传了，并且我可以通过http://192.168.112.200:3000/uploads/upload_897dac7bb52b9f82545e31f310848233.png（自己的ip：端口访问到）

4、插入图片时候报了如下错误
![image](https://user-images.githubusercontent.com/46664739/104400371-5af9c480-558d-11eb-80de-d0a8bf36b719.png)

**Comment by davidmehren** [comment]
Sorry, please use English to ask questions.

Also note that the log states that you didn't set `CMD_DOMAIN`, which should explain your issue.
