### ISSUE TITLE
Deploy on own domain and reverse proxy. Weird frontend behavior.

### ISSUE THREAD

**Issue by zaanposni** [hedgedoc/container#150]
When deploying hedgedoc on my domain with my own nginx proxy, I get a weird behavior on the frontend, buttons are not working and even guest notes are not working properly.
For example the login button does not open the popup.
Opening a guest note looks like this:
![grafik](https://user-images.githubusercontent.com/24491035/105626860-109d0100-5e33-11eb-8332-1bebbd1c0557.png)

**When deploying on my local machine everything works as expected compared to the demo server at `demo.hedgedoc.org`.**

I am deploying using the instruction in the readme
```
git clone https://github.com/hedgedoc/container.git hedgedoc-container
cd hedgedoc-contaienr
docker-compose up
```

```
$ docker -v
Docker version 20.10.2, build 2291f61
$ docker-compose -v
docker-compose version 1.27.3, build 4092ae5d
```

My local nginx configuration looks like this:
```
server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/keys/origin.pem;
    ssl_certificate_key /etc/nginx/keys/private.key;

    server_name docs.zaanposni.com note.zaanposni.com notes.zaanposni.com;

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:3000;
    }
}
```

Am I missing something? 
Is there a more detailed instruction on how to deploy hedgedoc on a domain?

**Comment by SISheogorath** [comment]
I would start with the nginx configuration as well as checking that you set up the required configuration parameters in your compose file. 

We have an official configuration guide for it these days: https://docs.hedgedoc.org/setup/reverse-proxy/

Most importantly: `CMD_DOMAIN`, `CMD_PROTOCOL_USESSL` and `CMD_URL_ADDPORT`.

**Comment by zaanposni** [comment]
Thanks for your response,
indeed I missed this part of the manual. Thanks.

However, the problem was something else
**Cloudflare Rocket Loader** failed.
Rocket Loader combines the websites javascript and returns them as fast as possible to the client.
This request in the browser failed and I simply had no Javascript 😄.
I should have discovered this on my own.
