### ISSUE TITLE
error on "sequelize db:migrate", container start is stuck

### ISSUE THREAD

**Issue by oupala** [hedgedoc/container#157]
I'm trying to instanciate a HedgeDoc container on OpenShift/K8S and I'm having some trouble in making it running.

The strange thing is that the deployement runs well when the database is a separate MariaDB.

The deployement runs well also when I deploy a container from my local Docker engine.

The main differences between the previous environments (which are working) and the one which is not working are :

| env  | platform                                      | database | OK/KO  |
| ---- | --------------------------------------------- | -------- | ------ |
| no 1 | OpenShift (container is **not** run as root)  | MariaDB  | OK     |
| no 2 | local Docker (container can be run as root)   | sqlite   | OK     |
| no 3 | OpenShift  (container is **not** run as root) | sqlite   | **KO** |

It appears that the container that works is starting well until it start the following database migration:

```
== 20200321153000-fix-account-deletion: migrating =======
```

And unlike other working environments, the following line never comes:

```
== 20200321153000-fix-account-deletion: migrated (0.692s)
```

I tried to launch it again from the container, but the process never ends.

Is there something special with this batch that could explain that is never ends with sqlite in a specific environment (when the container is not run as root.

**Comment by oupala** [comment]
It seems it is the only one requiring a child process:

```bash
grep child *
20200321153000-fix-account-deletion.js:const { spawnSync } = require('child_process')
```

**Comment by SISheogorath** [comment]
I'm currently working towards an official helm chart that should support OprnShift as well. It'll use postgresql and minio and. Not store any data in the container.

So far I have a first working version. I'll come back when I managed to organise it a bit more generalised version.

**Comment by oupala** [comment]
Some OpenShift platforms (ie. on premise) do not support helm charts. We should also support deployments using yaml templates.

**Comment by SISheogorath** [comment]
I would consider those platforms reasonable complex that they have the staff to make sure things work. Usually they also have different compliance requirements that we won't achieve with this image anyway.

I would like to work on the 80% use-case solution since the remaining 20% usually results in exploding complexity.

**Comment by nomaster** [comment]
I'm facing a similar issue where the same migration hangs, running Kubernetes on Azure using MariaDB

**Comment by SISheogorath** [comment]
There is no more installed squelize CLI.
