### ISSUE TITLE
changing permissions for upload dir on container start

### ISSUE THREAD

**Issue by ccoenen** [hedgedoc/container#25]
https://github.com/hackmdio/codimd-container/blob/393466f5ca6f1d4ae3f6103f6887b011900b51b4/resources/docker-entrypoint.sh#L43-L47

I would like to request to change the chmod from `700` to `u+rwx` instead.

Right now, The former also takes away `group` and `other` permissions while the latter more precisely does what it says in the comment above. I am not sure if this is by design, but it has a side effect for me: I'm using a reverse proxy to deliver the uploaded assets. Right now, I have to manually reset the directory's permission after each start of the container. Otherwise the proxy process wouldn't have read permissions in that directory.

**Comment by SISheogorath** [comment]
The original idea for this behavior is to prevent other processes (in case of being compromised) from snopping on user images. But we can might add a GID and allow to specify a group that is allowed to read the data in that directory.

Quite easy way to do that.

**Comment by ccoenen** [comment]
Yes, that's probably the better way. I would propose to default to gid 33, just because that's the default for `www-data` on ubuntu.

**Comment by dbrgn** [comment]
Hi hedgedoc maintainers. This still seems to be an issue. Any chance that someone can review #29 which proposes a fix?

**Comment by SISheogorath** [comment]
The mentioned PR need to be rebased, before it can be merged. In general it looks good.

**Comment by ccoenen** [comment]
> The mentioned PR need to be rebased, before it can be merged. In general it looks good.

I took the liberty of rebasing it. It needs a DCO, though.
