### ISSUE TITLE
Database cannot be reached. Try 1 of 30

### ISSUE THREAD

**Issue by prologic** [hedgedoc/container#289]
```#!console
$ docker run -i -t --rm -p 3000:3000 -e CMD_DB_URL=sqlite:///hedgedoc.db quay.io/hedgedoc/hedgedoc:1.9.2
/bin/sh: 1: git: not found
2022-02-19T05:48:51.198Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2022-02-19T05:48:51.199Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2022-02-19T05:48:51.564Z warn: 	Database cannot be reached. Try 1 of 30.
```

I assume sqlite is suppose to work as it is ia supported dialect?

**Comment by davidmehren** [comment]
It looks like sequelize has some issues parsing SQLite DB URLs when the filename directly follows three slashes.
`CMD_DB_URL=sqlite:///tmp/hedgedoc.db` and `CMD_DB_URL=sqlite://./hedgedoc.db` worked for me.

**Comment by prologic** [comment]
Thanks I'll give this another go tomorrow. Meanwhile I got CodiMD working. Is CodiMD the same as HedgeDoc? I'm getting confused between HackMD, CodiMD and HedgeDoc 😅

**Comment by SISheogorath** [comment]
@prologic I would recommend to have a look at: https://hedgedoc.org/history/

We tried to sum it up a bit, if questions remain, I can highly recommend our community chat: https://chat.hedgedoc.org/

**Comment by prologic** [comment]
> HedgeDoc is the community-driven fork of CodiMD, which is the open source counterpart to HackMD. Confused? Let us explain:

Ahh! This makes sense. I _might_ try and redo my setup to use HedgeDoc -- I kind of wanted to use SQLite anyway since my planned setup is intended to be small and I don't need a freak'n Network-enabled SQL database (_infact I really don't like using SQL databases :P_)

**Comment by prologic** [comment]
@davidmehren One issue I do have however with the HedgeDoc image is that there is no `VOLUME` in the `Dockerfile. Can we add one say at `VOLUME /data` so I can attach volumes to that? This is kind of important really.

**Comment by SISheogorath** [comment]
Uhm, you don't need to add a volume statement in order to attach volumes. Just tell docker to put a volume there and things happen by themselves. The opposite is the case, if you use the `VOLUME` statement, you can not not put a volume there, why it's often discouraged to be used nowadays.

**Comment by prologic** [comment]
Hmmm actually you are right, nevermind old habits 😅

**Comment by prologic** [comment]
I'm _hoping_ the "configuration" is largely the same between CodiMD and HedgeDoc here in terms of valid environment variables so 🤞

**Comment by prologic** [comment]
Hmmm still having an issue with the databse:

```
hedgedoc_hedgedoc.1.odacurfo5vls@dm6.mills.io    | 2022-02-19T22:58:44.676Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
hedgedoc_hedgedoc.1.odacurfo5vls@dm6.mills.io    | 2022-02-19T22:58:45.224Z warn: 	Database cannot be reached. Try 1 of 30.
hedgedoc_hedgedoc.1.odacurfo5vls@dm6.mills.io    | 2022-02-19T22:58:59.012Z info: 	HedgeDoc has been killed by signal, try to exit gracefully...
```

**Comment by prologic** [comment]
here's my setup:

```#!yaml
---

version: "3.8"

services:
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.2
    environment:
      - CMD_DB_URL=sqlite:///data/hedgedoc.db
      - CMD_ALLOW_ORIGIN=docs.mydomain.com
      - CMD_DOMAIN=docs.mydomain.com
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=true
      - CMD_USECDN=false
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_VIEWS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_GITHUB_CLIENTID=<redacted>
      - CMD_GITHUB_CLIENTSECRET=<redacted>
    networks:
      - traefik
    volumes:
      - data:/data
    deploy:
      placement:
        constraints:
          - "node.hostname == dm6.mydomain.com"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.hedgedoc.loadbalancer.server.port=3000"
        - "traefik.http.routers.hedgedoc.rule=Host(`docs.mydomain.com`)"
        - "traefik.http.routers.hedgedoc.priority=2"
      restart_policy:
        condition: any
      replicas: 1

networks:
  traefik:
    external: true

volumes:
  data:
    driver: local
```

**Comment by prologic** [comment]
Yeah so volumes are basically not working here:

```
$ dki -t --rm -p 3000:3000 -v hedgedoc_data:/data -e CMD_DB_URL=sqlite:///data/hedgedoc.db quay.io/hedgedoc/hedgedoc:1.9.2
/bin/sh: 1: git: not found
2022-02-19T23:19:16.175Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2022-02-19T23:19:16.177Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2022-02-19T23:19:16.542Z warn: 	Database cannot be reached. Try 1 of 30.
```

The worst part here is there's not actual error. Why not? If there's a problem can't we log a proper error?

I suspect this _mioght- have something to do with the UID/GID the `hedgedoc` (This is NodeJS right?) is running as.

**Comment by SISheogorath** [comment]
That sounds reasonable, regular docker volumes take the UID of the directory in the container. However, this directory doesn't exist and therefore will be created with UID 0. You can set it to 10000 and it should fix it.

**Comment by prologic** [comment]
Yes this is why I stated [my comment](https://github.com/hedgedoc/container/issues/289#issuecomment-1046119160) above. I _believe_ your statement is incorrect about Docker volumes. Unless things have changed, I've been doing this for a while, and had to do something similar myself in Yarn.social's own Docker image too to support Synology NAS(es) and basically this kind of setup.

As we speak I'm forking this repo and making the necessary changes. 🤞

**Comment by prologic** [comment]
Just wanted to update this discussion to say that for the time being I've given up on trying to make SQLite work with Hedgedoc. Somehow the Docker image / `Dockerfile` is not setup correctly to support this with Docker volumes, but I don't have enough bandwidth right not to figure that out.

I've set-up my Hedgedoc instance in a Docker Swarm cluster mostly as per the above but with a PostgresSQL database (_for now_).

Thanks!
