### ISSUE TITLE
Add uploads dir to volumes in example docker-compose.yml

### ISSUE THREAD

**Issue by pirate** [hedgedoc/container#39]
Would be nice to have the volume for image uploads exposed in the `docker-compose.yml` file, had to dig through a bit of code to figure out exactly which path to mount on our setup.

**Comment by SISheogorath** [comment]
Like this?

https://github.com/codimd/container/blob/2f5909aed675fb4986f920fa478c154bf721de1a/docker-compose.yml#L63-64

**Comment by pirate** [comment]
Yes, but as a normal volume that gets persisted:

```yaml
volumes:
    ...
    - "./data/uploads:/codimd/public/uploads"
```

**Comment by numero-six** [comment]
It would be nice but inconsistent with the fact that this docker-compose defaults to 

```
        "imageUploadType": "imgur"
```

as you can see in `resources/config.json`.

**Comment by numero-six** [comment]
> It would be nice but inconsistent with the fact that this docker-compose defaults to

Suggested !83
