### ISSUE TITLE
Sequelize Binary Does Not Exist

### ISSUE THREAD

**Issue by dargmuesli** [hedgedoc/container#46]
I receive `error: exec: "./node_modules/.bin/sequelize": stat ./node_modules/.bin/sequelize: no such file or directory` originating from the following line, but the server starts nevertheless, so I'll leave this here as a note.

https://github.com/codimd/container/blob/19b8a226875075020e61d05c57b8cf94eac8aafa/resources/docker-entrypoint.sh#L27

**Comment by hugopeixoto** [comment]
Without `sequelize db:migrate` running, your database won't have the proper schema, so I think we should treat this as an error and stop the execution.

I think this can be achieved by adding `set -e` to `docker-entrypoint.sh`. We just need to make sure that none of the other commands can fail.

**Comment by SISheogorath** [comment]
No more sequlize-cli, so this problem should not appear again.
