### ISSUE TITLE
Update spam on the release channel

### ISSUE THREAD

**Issue by MeidoDev** [hedgedoc/container#496]
For about two weeks now, a new image of version 1.9.9 is getting pushed to the registry every day. This happens because a bot bumps up the version of `docker/build-push-action` once a day, triggering a new build. Functionally, the image stays the same.

This behavior has been a minor nuisance for me, since it triggers [watchtower](https://containrrr.dev/watchtower/) to update or notify that a new version is available. Other, similar tools are most likely behaving the same.

I'd recommend to introduce a tagging strategy for this repository and changing the release action so it only triggers from new tags.

**Comment by SISheogorath** [comment]
Looking at the repository changelog, it's not that frequent. on average somewhere between once to twice per week.

![image](https://github.com/hedgedoc/container/assets/8719867/858d0aa2-326d-4e87-814d-d7921daba639)

**Comment by MeidoDev** [comment]
I'm using `quay.io/hedgedoc/hedgedoc:1.9.9-alpine`.
You are right, though, the updates didn't happen as often as I perceived them. (I have watchtower set to notify only, and apparently it keeps notifying you about the same new image until you update the container)

Thanks for your reply and @mrdrogdrog 's fix, I'm closing this issue.
